"""empty message

Revision ID: 3ed1a772837a
Revises: 
Create Date: 2024-11-06 20:53:02.943228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed1a772837a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombresCliente', sa.String(length=250), nullable=True),
    sa.Column('apellidosCliente', sa.String(length=180), nullable=True),
    sa.Column('cedula', sa.String(length=180), nullable=True),
    sa.Column('direccion', sa.String(length=180), nullable=True),
    sa.Column('telefono', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=True),
    sa.Column('descripcion', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresasProveedoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('encargadoDespacho', sa.String(length=180), nullable=True),
    sa.Column('telefonoEmpresa', sa.String(length=180), nullable=True),
    sa.Column('direccionEmpresa', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=250), nullable=True),
    sa.Column('apellidos', sa.String(length=250), nullable=True),
    sa.Column('correo', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('fechaContratoInicio', sa.DateTime(), nullable=True),
    sa.Column('fechaContratoFinalizado', sa.DateTime(), nullable=True),
    sa.Column('Rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Rol'], ['Rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreProv', sa.String(length=180), nullable=True),
    sa.Column('apellidoProv', sa.String(length=180), nullable=True),
    sa.Column('cedula', sa.String(length=180), nullable=True),
    sa.Column('telefonoProv', sa.String(length=180), nullable=True),
    sa.Column('direccionProv', sa.String(length=180), nullable=True),
    sa.Column('empresasProveedoras', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresasProveedoras'], ['empresasProveedoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subcategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('Categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Categoria'], ['Categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreProd', sa.String(length=250), nullable=True),
    sa.Column('medidaProd', sa.Integer(), nullable=True),
    sa.Column('unidadMedidaProd', sa.String(length=250), nullable=True),
    sa.Column('precioUnidadProd', sa.Float(), nullable=True),
    sa.Column('costoProd', sa.Float(), nullable=True),
    sa.Column('ivaProd', sa.Float(), nullable=True),
    sa.Column('porcentajeGanancia', sa.Float(), nullable=True),
    sa.Column('unidadesTotalesProd', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=250), nullable=True),
    sa.Column('marcaProd', sa.String(length=250), nullable=True),
    sa.Column('proveedor', sa.Integer(), nullable=True),
    sa.Column('subcategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor'], ['Proveedor.id'], ),
    sa.ForeignKeyConstraint(['subcategoria'], ['Subcategoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaVenta', sa.DateTime(), nullable=True),
    sa.Column('totalVenta', sa.Float(), nullable=True),
    sa.Column('empleado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado'], ['Empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleVentaProductos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precioUnidad', sa.Float(), nullable=True),
    sa.Column('cedula', sa.String(length=180), nullable=True),
    sa.Column('direccion', sa.String(length=180), nullable=True),
    sa.Column('telefono', sa.String(length=180), nullable=True),
    sa.Column('venta', sa.Integer(), nullable=True),
    sa.Column('producto', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['producto'], ['Producto.id'], ),
    sa.ForeignKeyConstraint(['venta'], ['Venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablaDePagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodosDePago', sa.String(length=250), nullable=True),
    sa.Column('totalAPagar', sa.Numeric(precision=19, scale=0), nullable=True),
    sa.Column('fechaDePago', sa.DateTime(), nullable=True),
    sa.Column('estadoPago', sa.String(length=250), nullable=True),
    sa.Column('venta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venta'], ['Venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaGeneracionFactura', sa.DateTime(), nullable=True),
    sa.Column('impuestosFactura', sa.Numeric(precision=19, scale=0), nullable=True),
    sa.Column('tablaDePagos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tablaDePagos'], ['tablaDePagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Factura')
    op.drop_table('tablaDePagos')
    op.drop_table('detalleVentaProductos')
    op.drop_table('Venta')
    op.drop_table('Producto')
    op.drop_table('Subcategoria')
    op.drop_table('Proveedor')
    op.drop_table('Empleado')
    op.drop_table('empresasProveedoras')
    op.drop_table('Rol')
    op.drop_table('Cliente')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
